export const TWEET_LIST_REQUEST = 'TWEET_LIST_REQUEST'
export const TWEET_LIST_SUCCESS = 'TWEET_LIST_SUCCESS'
export const TWEET_LIST_FAIL = 'TWEET_LIST_FAIL'

export const TWEET_USER_LIST_REQUEST = 'TWEET_USER_LIST_REQUEST'
export const TWEET_USER_LIST_SUCCESS = 'TWEET_USER_LIST_SUCCESS'
export const TWEET_USER_LIST_FAIL = 'TWEET_USER_LIST_FAIL'

export const TWEET_LIKE_BY_USER_REQUEST = 'TWEET_LIKE_BY_USER_REQUEST'
export const TWEET_LIKE_BY_USER_SUCCESS = 'TWEET_LIKE_BY_USER_SUCCESS'
export const TWEET_LIKE_BY_USER_FAIL = 'TWEET_LIKE_BY_USER_FAIL'

export const TWEET_POST_REQUEST = 'TWEET_POST_REQUEST'
export const TWEET_POST_SUCCESS = 'TWEET_POST_SUCCESS'
export const TWEET_POST_FAIL = 'TWEET_POST_FAIL'
export const TWEET_POST_RESET = 'TWEET_POST_RESET'

export const TWEET_LIKE_REQUEST = 'TWEET_LIKE_REQUEST'
export const TWEET_LIKE_SUCCESS = 'TWEET_LIKE_SUCCESS'
export const TWEET_LIKE_FAIL = 'TWEET_LIKE_FAIL'
export const TWEET_LIKE_RESET = 'TWEET_LIKE_RESET'

export const TWEET_DISLIKE_REQUEST = 'TWEET_DISLIKE_REQUEST'
export const TWEET_DISLIKE_SUCCESS = 'TWEET_DISLIKE_SUCCESS'
export const TWEET_DISLIKE_FAIL = 'TWEET_DISLIKE_FAIL'
export const TWEET_DISLIKE_RESET = 'TWEET_DISLIKE_RESET'

export const TWEET_COMMENT_REQUEST = 'TWEET_COMMENT_REQUEST'
export const TWEET_COMMENT_SUCCESS = 'TWEET_COMMENT_SUCCESS'
export const TWEET_COMMENT_FAIL = 'TWEET_COMMENT_FAIL'
export const TWEET_COMMENT_RESET = 'TWEET_COMMENT_RESET'

export const TWEET_RT_REQUEST = 'TWEET_RT_REQUEST'
export const TWEET_RT_SUCCESS = 'TWEET_RT_SUCCESS'
export const TWEET_RT_FAIL = 'TWEET_RT_FAIL'
export const TWEET_RT_RESET = 'TWEET_COMMENT_RESET'

export const TWEET_DETAILS_REQUEST = 'TWEET_DETAILS_REQUEST'
export const TWEET_DETAILS_SUCCESS = 'TWEET_DETAILS_SUCCESS'
export const TWEET_DETAILS_FAIL = 'TWEET_DETAILS_FAIL'

export const TWEET_COMMENT_LIST_REQUEST = 'TWEET_COMMENT_LIST_REQUEST'
export const TWEET_COMMENT_LIST_SUCCESS = 'TWEET_COMMENT_LIST_SUCCESS'
export const TWEET_COMMENT_LIST_FAIL = 'TWEET_COMMENT_LIST_FAIL'

export const TWEET_DELETE_REQUEST = 'TWEET_DELETE_REQUEST'
export const TWEET_DELETE_SUCCESS = 'TWEET_DELETE_SUCCESS'
export const TWEET_DELETE_FAIL = 'TWEET_DELETE_FAIL'
export const TWEET_DELETE_RESET = 'TWEET_DELETE_RESET'